### ISSUE TITLE
SysInfo, GLCanvas, Controls4U, SurfaceCtrl examples are failing to build due to incorrect file paths.

### ISSUE THREAD

**Issue by ismail-yilmaz** [ultimatepp/UppHub#16]
@mirek-fidler 
@klugier 

The reason is the paths to `.iml` and `.lay` files are incorrect under UppHub. They should be prepended with `examples/` (I am not sure if this is the solution or a workaround though).

I've opened this issue here, because AFAIK some of us (Mirek, Klugier?) have access to these repos and can fix them. 

I have also opened an issue in SurfaceCtrl repo, reporting this issue to Xemuth.

**Comment by klugier** [comment]
This was fixed long time ago.
